nelmio_cors:
    defaults:
        origin_regex: true
        allow_origin: ['%env(CORS_ALLOW_ORIGIN)%']
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
        allow_headers: ['Content-Type', 'Authorization']
        expose_headers: ['Link']
        max_age: 3600
    paths:
        '^/api/':
            allow_origin: ['*']
            allow_headers: ['X-Custom-Auth']
            allow_methods: ['GET']
            max_age: 3600
        '^/api/import':
            allow_origin: ['%env(ADMIN_CORS_ALLOW_ORIGIN)%']
            allow_headers: ['X-Custom-Auth']
            allow_methods: ['POST', 'PUT', 'GET']
            max_age: 3600
        '^/api/indexation':
            allow_origin: ['%env(ADMIN_CORS_ALLOW_ORIGIN)%']
            allow_headers: ['X-Custom-Auth']
            allow_methods: ['POST', 'PUT', 'GET']
            max_age: 3600
        '^/login':
            allow_origin: ['%env(string:ADMIN_CORS_ALLOW_ORIGIN)%']
            allow_methods: ['POST']
            max_age: 3600
        '^/logout':
            allow_origin: ['%env(ADMIN_CORS_ALLOW_ORIGIN)%']
            allow_methods: ['POST']
            max_age: 3600
        '^/': null
